BackendBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        plainPassword:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: plain_password
        firstName:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: last_name
    lifecycleCallbacks: {  }
